# Generated by Django 4.0.2 on 2022-02-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('name',)},
        ),
    ]
